version: 3.10.7
services:
  web:
    depends_on:
      - postgres_db
    build: 
      context: ./fs
      dockerfile: Dockerfile
    image: savior:1.1
    environment:
      - PORT=8001
    env_file:
      - fs/.env
    ports:
      - "8001:8001"
    command: sh -c "chmod +x /app/migrate.sh && /app/migrate.sh && /app/entrypoint.sh"
    volumes:
      - staticfiles:/app/staticfiles/
      
  postgres_db:
    image: postgres
    restart: always
    env_file:
      - fs/.env
    command: -p 25060
    expose:
      - 25060
    ports:
      - "25060:25060"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis_db:
    image: redis
    restart: always
    expose:
      - 25061
    ports:
      - "25061:25061"
    volumes:
        - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 25061

volumes:
  staticfiles:
    external: true
  postgres_data:
  redis_data: