version: 3.10.7
services:
  web:
    depends_on:
      - postgres_db
    build: 
      context: ./fs
      dockerfile: Dockerfile
    image: savior:1.1
    environment:
      - PORT=8020
    env_file:
      - fs/.env
    ports:
      - "8001:8020"
    command: sh -c "chmod +x /app/migrate.sh && /app/migrate.sh && /app/entrypoint.sh"
  

  postgres_db:
    image: postgres
    env_file:
      - fs/.env
    command: -p 5433
    expose:
      - 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: