apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gcr-push-keys-list-deployments
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: container.deployments.list
subjects:
- kind: ServiceAccount
  name: gcr-push-keys
  namespace: default
