kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: container-cluster-role
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings"]
  verbs: ["create"]
