# Generated by Django 4.1.3 on 2022-11-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='like',
            new_name='liked',
        ),
    ]
