# Generated by Django 4.1.3 on 2022-11-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-created_at',)},
        ),
    ]
