# Generated by Django 4.1.6 on 2023-02-13 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
        ('zakat_posts', '__first__'),
        ('IWatch', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugg2Savior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField(blank=True, max_length=500)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('savior_adviser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savior_adviser', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ReportZakatPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, max_length=500)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reported_zp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_zp', to='zakat_posts.zakatposts')),
                ('zakat_reporter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zakat_reporter', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSaviorProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, max_length=500)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('savior_reporter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savior_reporter', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ReportIWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, max_length=500)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('iwatch_reporter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iwatch_reporter', to='profiles.profile')),
                ('reported_iw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_iw', to='IWatch.iwatch')),
            ],
        ),
    ]
