# Generated by Django 4.1.6 on 2023-02-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_rename_report_reportiwatch_problem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportsaviorproblem',
            old_name='report',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='reportzakatpost',
            old_name='report',
            new_name='problem',
        ),
        migrations.RemoveField(
            model_name='reportsaviorproblem',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='reportzakatpost',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='sugg2savior',
            name='updated',
        ),
    ]
