# Generated by Django 4.1.6 on 2023-02-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_rename_report_reportsaviorproblem_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportiwatch',
            name='Recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportzakatpost',
            name='Recorded',
            field=models.BooleanField(default=False),
        ),
    ]
