# Generated by Django 4.1.6 on 2023-02-13 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IWatch', '__first__'),
        ('zakat_posts', '__first__'),
        ('support', '0006_alter_reportiwatch_reported_iw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportiwatch',
            name='reported_iw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_iw', to='IWatch.iwatch'),
        ),
        migrations.AlterField(
            model_name='reportzakatpost',
            name='reported_zp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_zp', to='zakat_posts.zakatposts'),
        ),
    ]
