# Generated by Django 4.1.6 on 2023-02-13 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '__first__'),
        ('support', '0007_alter_reportiwatch_reported_iw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportiwatch',
            name='iwatch_reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iwatch_reporter', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='reportsaviorproblem',
            name='savior_reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savior_reporter', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='reportzakatpost',
            name='zakat_reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakat_reporter', to='profiles.profile'),
        ),
    ]
