# Generated by Django 4.1.6 on 2023-02-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '__first__'),
        ('support', '0008_alter_reportiwatch_iwatch_reporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugg2savior',
            name='savior_adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savior_adviser', to='profiles.profile'),
        ),
    ]
