# Generated by Django 4.1.6 on 2023-02-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_alter_sugg2savior_savior_adviser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsaviorproblem',
            name='problem',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='sugg2savior',
            name='suggestion',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
