apiVersion: v1
kind: Service
metadata:
  name: savior-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: savior-deployment

    
# annotations:
#       cloud.google.com/neg: '{"ingress": true}'