apiVersion: v1
kind: ReplicationController
metadata:
  name: celery-configuration
  labels:
    component: celery
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: savior-deployment
        component: savior-deployment
    spec:
      terminationGracePeriodSeconds: 86400

      containers:
      - name: savior
        image: registry.digitalocean.com/savior/savior:latest
        imagePullPolicy: IfNotPresent
        resources:
            requests:
              cpu: "100m"
              memory: "500M"
            limits:
              cpu: "500m"
              memory: "1000M"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 120

        command: [ "/bin/sh", "-c" ]
        args: [ "/opt/venv/bin/celery -A family_savior worker -l INFO;" ]
        envFrom:
          - secretRef:
              name: savior-prod-secret
        env:
          - name: PORT
            value: "8000"
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: savior

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: celery-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-configuration
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50