apiVersion: v1
kind: ReplicationController
metadata:
  name: celery-configuration
  labels:
    component: celery
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: savior-deployment
        component: savior-deployment
    spec:
      containers:
      - name: savior
        image: registry.digitalocean.com/savior/savior:latest
        imagePullPolicy: Always
        command: [ "/bin/sh", "-c" ]
        args: [ "/opt/venv/bin/celery -A family_savior worker -l INFO;" ]
        envFrom:
          - secretRef:
              name: savior-prod-secret
        env:
          - name: PORT
            value: "8000"
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: savior

