apiVersion: apps/v1
kind: Deployment
metadata:
  name: savior-deployment
  labels:
    app: savior-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: savior-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: savior-deployment
    spec:
      containers:
      - name: savior
        image: registry.digitalocean.com/savior/savior:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: savior-prod-secret
        env:
          - name: PORT
            value: "8000"
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: savior

---

apiVersion: v1
kind: Service
metadata:
  name: savior-deployment
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: savior-deployment

