apiVersion: apps/v1
kind: Deployment
metadata:
  name: savior-deployment
  labels:
    app: savior-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: savior-deployment
  template:
    metadata:
      labels:
        app: savior-deployment
    spec:
      containers:
      - name: savior
        image: registry.digitalocean.com/savior/savior:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: savior-prod-secret
        resources:
            requests:
              cpu: "100m"
              memory: "100M"
            limits:
              cpu: "150m"
              memory: "200M"
        ports:
          - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 120
        env:
          - name: PORT
            value: "8000"
      imagePullSecrets:
        - name: savior

---

apiVersion: v1
kind: Service
metadata:
  name: savior-deployment
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000
    
  selector:
    app: savior-deployment

