apiVersion: apps/v1
kind: Deployment
metadata:
  name: savior-deployment
  labels:
    app: savior-deployment
spec:
  replicas: 2 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: savior-deployment
  template:
    metadata:
      labels:
        app: savior-deployment
    spec:    
      containers:
      - name: savior
        image: registry.digitalocean.com/savior-container/savior:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: savior-prod-secret
        resources:
          requests:
            cpu: "100m"
            memory: "500M"
          limits:
            cpu: "500m"
            memory: "1000M"
        env:
          - name: PORT
            value: "8000"
        ports:
        - containerPort: 8000

      imagePullSecrets:
        - name: savior-container 

---

apiVersion: v1
kind: Service
metadata:
  name: savior-deployment
  # annotations:
  #   service.beta.kubernetes.io/do-loadbalancer-name: "savior-loadbalancer"
  #   service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
  #   service.beta.kubernetes.io/do-loadbalancer-certificate-id: "9a72fa32-d678-48e8-a2b8-f58ae16253d2" 

  #   service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
  #   service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
  #   service.beta.kubernetes.io/do-loadbalancer-enable-backend-keepalive: "true"

  #   service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-type: "cookies"
  #   service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-name: "savior-cookies"
  #   service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-ttl: "60"

spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000
    
  selector:
    app: savior-deployment

