# Generated by Django 4.1.3 on 2022-12-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='update',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='profile',
            name='post_no',
            field=models.IntegerField(default=0),
        ),
    ]
