# Generated by Django 4.1.3 on 2022-12-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_update_profile_updated_profile_post_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post_no',
            field=models.IntegerField(default=1),
        ),
    ]
