# Generated by Django 4.1.3 on 2022-12-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakatPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeker', models.CharField(blank=True, max_length=100)),
                ('number1', models.IntegerField(default=0)),
                ('cnic1', models.ImageField(upload_to='cnic_image')),
                ('spouse_name', models.CharField(blank=True, max_length=100)),
                ('number2', models.IntegerField(default=0)),
                ('cnic2', models.ImageField(upload_to='cnic_image')),
                ('no_of_children', models.IntegerField(default=0)),
                ('video1', models.FileField(blank=True, upload_to='zakat_video')),
                ('video2', models.FileField(blank=True, upload_to='zakat_video')),
                ('AI_varified', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('expected_money', models.IntegerField(default=0)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('donor', models.ManyToManyField(blank=True, related_name='donors', to='profiles.profile')),
            ],
        ),
    ]
