# Generated by Django 4.1.3 on 2022-12-20 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakatPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeker', models.CharField(blank=True, max_length=100)),
                ('number1', models.IntegerField(blank=True, default=0)),
                ('cnic1', models.ImageField(blank=True, upload_to='cnic_image')),
                ('spouse_name', models.CharField(blank=True, max_length=100)),
                ('number2', models.IntegerField(blank=True, default=0)),
                ('cnic2', models.ImageField(blank=True, upload_to='cnic_image')),
                ('no_of_children', models.IntegerField(default=0)),
                ('video1', models.FileField(blank=True, upload_to='zakat_video')),
                ('video2', models.FileField(blank=True, upload_to='zakat_video')),
                ('varified', models.BooleanField(blank=True, default=False)),
                ('paid', models.BooleanField(blank=True, default=False)),
                ('expected_money', models.IntegerField(default=0)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('donor', models.ManyToManyField(blank=True, related_name='donors', to='profiles.profile')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ZakatPostsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakat_posts_comments', to='zakat_posts.zakatposts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakat_posts_user_comments', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='zakat_posts.zakatposts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DownVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to='zakat_posts.zakatposts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
