# Generated by Django 4.1.3 on 2022-12-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakatposts',
            name='post_no',
            field=models.IntegerField(default=0),
        ),
    ]
