# Generated by Django 4.1.3 on 2022-12-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakatposts',
            name='cnic1',
        ),
        migrations.RemoveField(
            model_name='zakatposts',
            name='cnic2',
        ),
        migrations.RemoveField(
            model_name='zakatposts',
            name='no_of_children',
        ),
        migrations.RemoveField(
            model_name='zakatposts',
            name='number1',
        ),
        migrations.RemoveField(
            model_name='zakatposts',
            name='number2',
        ),
        migrations.RemoveField(
            model_name='zakatposts',
            name='spouse_name',
        ),
        migrations.AlterField(
            model_name='zakatposts',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zakatposts',
            name='paid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='zakatposts',
            name='video2',
            field=models.FileField(upload_to='zakat_video'),
        ),
    ]
