# Generated by Django 4.1.3 on 2022-12-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_posts', '0002_zakatposts_post_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakatposts',
            name='post_no',
        ),
    ]
