# Generated by Django 4.1.3 on 2022-12-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_posts', '0002_remove_zakatposts_cnic1_remove_zakatposts_cnic2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakatposts',
            name='satisfied',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
