# Generated by Django 4.1.3 on 2022-12-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_posts', '0003_zakatposts_satisfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakatposts',
            name='varified',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
