# Generated by Django 4.1.3 on 2022-12-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_posts', '0003_remove_zakatposts_post_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakatposts',
            name='post_number',
            field=models.IntegerField(default=0),
        ),
    ]
