# Generated by Django 4.1.3 on 2022-12-03 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_avatar'),
        ('zakat_posts', '0004_alter_zakatposts_options_alter_zakatposts_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakatposts',
            name='AI_varified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='zakatposts',
            name='cnic1',
            field=models.ImageField(blank=True, upload_to='cnic_image'),
        ),
        migrations.AlterField(
            model_name='zakatposts',
            name='cnic2',
            field=models.ImageField(blank=True, upload_to='cnic_image'),
        ),
        migrations.AlterField(
            model_name='zakatposts',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='zakatposts',
            name='number1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='zakatposts',
            name='number2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='zakatposts',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
