# Generated by Django 4.1.3 on 2022-12-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_posts', '0004_alter_zakatposts_varified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zakatposts',
            old_name='expected_money',
            new_name='needed_money',
        ),
    ]
