# Generated by Django 4.1.3 on 2022-12-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakat_posts', '0005_alter_zakatposts_ai_varified_alter_zakatposts_cnic1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakatposts',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
