# Generated by Django 4.1.3 on 2022-12-18 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_avatar'),
        ('zakat_posts', '0009_alter_zakatposts_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zakatposts',
            old_name='AI_varified',
            new_name='varified',
        ),
        migrations.AlterField(
            model_name='zakatpostscomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakat_posts_comments', to='zakat_posts.zakatposts'),
        ),
        migrations.AlterField(
            model_name='zakatpostscomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakat_posts_user_comments', to='profiles.profile'),
        ),
    ]
