name: Deploy Savior 

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ "Deployment" ]
  pull_request: 
    branches: [ "Deployment" ]
  

jobs: 
  # test_django_job:
    # uses: Savior-Social/Savior/.github/workflows/test-django.yaml@Deployment
  build:
    runs-on: ubuntu-latest
    # needs: [test_django_job]
    env: 
      CONTAINER_NAME: savior-container
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: LOGIN TO DO REGISTRY
      run: doctl registry login 
    - name: Build conainer Image
      working-directory: ./fs
      run: |
        docker build -f Dockerfile \
          -t registry.digitalocean.com/${{ env.CONTAINER_NAME }}/savior:latest \
          -t registry.digitalocean.com/${{ env.CONTAINER_NAME }}/savior:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
          . 
    - name: Push container Image
      run: |
        docker push registry.digitalocean.com/${{ env.CONTAINER_NAME }}/savior --all-tags
    - name: k8s cluster kubeconfig file short-live creds
      run: | 
        doctl kubernetes cluster kubeconfig save savior-cluster

    - name: update deployment secrets
      run: |
        cat << EOF >> fs/.env
        ABSOLUTE_PATH=app
        USE_PRODUCTION=True
        TESTING=False
        DO_REDIS_URL=${{ secrets.DO_REDIS_URL }}
        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DJANGO_ALLOWED_HOSTS=${{ secrets.ALLOWED_HOST }}
        DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}
        DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
        DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
        DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}
        DJANGO_SUPERUSER_FULLNAME=${{ secrets.DJANGO_SUPERUSER_FULLNAME }}
        DJANGO_SUPERUSER_RELIGION=${{ secrets.DJANGO_SUPERUSER_RELIGION }}
        DJANGO_SUPERUSER_GENDER=Male
        DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} 
        POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
        EMAIL_USER=${{ secrets.EMAIL_USER }} 
        EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
        EOF
        kubectl delete secret savior-prod-secret
        kubectl create secret generic savior-prod-secret --from-env-file=fs/.env

    - name: update Deployment Image
      run: |
        kubectl set image deployment/savior-deployment savior=registry.digitalocean.com/${{ env.CONTAINER_NAME }}/savior:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}

    - name: wait for rollout to finish
      run: |
        kubectl rollout status deployment/savior-deployment
        
    - name: Migrate Database
      run: |
        export SINGLE_POD_NAME=$(kubectl get pod -l app=savior-deployment -o jsonpath="{.items[0].metadata.name}")
        kubectl exec -i $SINGLE_POD_NAME -- bash /app/migrate.sh 
        kubectl exec -i $SINGLE_POD_NAME -- bash /app/collectstatic.sh  
        kubectl exec -i $SINGLE_POD_NAME -- bash /app/superuser.sh
        kubectl apply -f k8s/apps/replicationcontrollers.yaml


