name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ Deployment ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: savior
      PROJECT_ID: high-function-378716
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
    
    - name: Build Docker Image
      working-directory: ./fs
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth login --no-launch-browser
        gcloud auth configure-docker --quiet
        with:
          4/0AWtgzh62vtNxEy8HwVSzJnzBMlQ5boDxeXxCtgbyYOpsiBbtc3QfMYo7kio7WA-JXqAhyA
          
        
    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: v0.1
      run: |-
        docker tag $IMAGE_NAME:latest asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
