name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ Deployment ]

jobs:
  job_id: 
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: savior
      PROJECT_ID: high-function-378716

    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/941419757436/locations/global/workloadIdentityPools/savior/attribute.repository/famior01/savior-clone'
        service_account: 'github-action@high-function-378716.iam.gserviceaccount.com'

    - name: Build Docker Image
      working-directory: ./fs
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker savior --quiet
        
    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: v0.1
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG